config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get "/menu", to: "items#index"
  resources :items, only: [:show, :index]

  resources :categories do
    resources :items, only: [:show, :index]
  end

  get "/cart", to: "cart#index"
  post "/cart", to: "cart#create"
  delete "/cart", to: "cart#delete"
  put "/cart", to: "cart#update"

  resources :orders, only: [:create, :index, :show, :update]

  get "/login", to: "sessions#new", :as => "login"
  post "/login", to: "sessions#create"
  get "/logout", to: 'sessions#destroy'
  delete "/logout", to: 'sessions#destroy'

  resources :users, only: [:show]

  namespace 'admin' do
    get '/', to: 'dashboard#index', as: '/'
    resources :items
    resources :categories
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title, :description, :price, presence: true
  has_attached_file :picture,
                    :styles => { :large => "960x960",
                                 :medium => "300x300>",
                                 :thumb => "100x100>" },
                    :default_url => "public/seed_photos/:style/missing.png"
  validates_attachment_content_type :picture,
                                    :content_type => /\Aimage\/.*\Z/
  has_many :orders
  has_many :items_categories
  has_many :categories, :through => :items_categories
  enum status: %w(active retired)
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < AdminController

  def index
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @items = Item.all
    end
  end

  def edit
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @item = Item.find(params[:id])
      @categories = @item.categories
      render :edit
    end
  end

  def new
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @item = Item.new
      @categories = Category.all
    end
  end

  def create
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @item = Item.new(item_params)

      @categories = params.select{ |k,v| k.include?("ItemsCategory") }.values[0].select{ |k,v| v == "1" }.keys

      if @item.save
        @categories.each do |category|
          @item.items_categories.create(category_id: Category.find_by(title: category).id)
        end
        redirect_to admin_items_path
      else
        render :new
      end
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.retired!
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :picture)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.active
  end

  def post
    
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/views/admin/items/_form.html.erb
<div input class="textbox">

<%= form_for @item,
             url: {action: "create", controller: "admin/items"},
             html: {:multipart => true} do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :picture %>
  <%= f.file_field :picture %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label "Categories" %>

  <% @categories.each do |category| %>
    <%= f.label category.title %>
    <%= check_box @item.items_categories, category.title %>
  <% end %>
  <%= f.submit %>

<% end %>

</div>

app/views/admin/items/edit.html.erb
<h1>Edit your item!</h1>

<%= render 'form' %>

<%= link_to "Retire Item", {controller: "admin/items", action: "update", status: "retire" } , :method=>:put  %>

app/views/admin/items/index.html.erb
Admin Item Index

<li> <%= link_to 'Add Item', new_admin_item_path%> </li>

<div id='items'>
  <% @items.each do |item| %>
    <div id="item_title"><%= item.title %></div>
    <div id="description"><%= item.description %></div>
    <div id="price"><%= number_to_currency(item.price) %></div>
    <div id="item_edit"> <td><%= link_to "Edit Item", edit_admin_item_path(item) %></td>
    <div id="item_view"> <td><%= link_to "View Item", item_path(item) %></td>
  <% end %>
</div>

app/views/admin/items/new.html.erb
<h1>Create a new item!</h1>

<%= render 'form' %>