config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get "/menu", to: "items#index"
  resources :items, only: [:show, :index]

  resources :categories do
    resources :items, only: [:show, :index]
  end

  get "/cart", to: "cart#index"
  post "/cart", to: "cart#create"
  delete "/cart", to: "cart#delete"
  put "/cart", to: "cart#update"

  resources :orders, only: [:create, :index, :show, :update]

  get "/login", to: "sessions#new", :as => "login"
  post "/login", to: "sessions#create"
  get "/logout", to: 'sessions#destroy'
  delete "/logout", to: 'sessions#destroy'

  resources :users, only: [:show]

  namespace 'admin' do
    get '/', to: 'dashboard#index', as: '/'
    resources :items
    resources :categories
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title, :description, :price, presence: true
  has_attached_file :picture,
                    :styles => { :large => "960x960",
                                 :medium => "300x300>",
                                 :thumb => "100x100>" },
                    :default_url => "public/seed_photos/:style/missing.png"
  validates_attachment_content_type :picture,
                                    :content_type => /\Aimage\/.*\Z/
  has_many :orders
  has_many :items_categories
  has_many :categories, :through => :items_categories
  enum status: %w(active retired)
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < AdminController

  def index
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @items = Item.all
    end
  end

  def edit
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @item = Item.find(params[:id])
      @categories = @item.categories
      render :edit
    end
  end

  def new
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @item = Item.new
      @categories = Category.all
    end
  end

  def create
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @item = Item.new(item_params)

      @categories = params.select{ |k,v| k.include?("ItemsCategory") }.values[0].select{ |k,v| v == "1" }.keys

      if @item.save
        @categories.each do |category|
          @item.items_categories.create(category_id: Category.find_by(title: category).id)
        end
        redirect_to admin_items_path
      else
        render :new
      end
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.retired!
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :picture)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.active
  end

  def post
    
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>

<% end %>

app/views/items/_item.html.erb
<div class="item">

    <div class="header">
        <%= link_to item.title, item %>
    </div>

    <div class="picture">
      <%= image_tag item.picture.url(:medium) %>
    </div>

    <div class="description">
        <%= item.description %>
    </div>

    <div class="price">
        <%= number_to_currency(item.price) %>
    </div>

    <div class="button">
      <%= button_to "Add To Cart", cart_path(item_id: item) %> </p>
    </div>

</div>

app/views/items/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div id='items'>
  <%= render @items %>
</div>

app/views/items/new.html.erb
<h1>Create a new item!</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="item">

    <div class="header">
        <%= @item.title %>
    </div>

    <div class="picture">
      <%= image_tag @item.picture.url(:large) %>
    </div>

    <div class="description">
        <%= @item.description %>
    </div>

    <div class="price">
        <%= number_to_currency(@item.price) %>
    </div>

    <div class="button">
      <%= button_to "Add To Cart", cart_path(item_id: @item) %> </p>
    </div>

    <% if current_user && current_user.admin? %>

    <div class="status">
      This item is currently: <%= @item.status %>
    </div>

    <div class="edit_button">
      <%= link_to "Edit Item", {controller: "admin/items", action: "edit" } , :method => "put"  %>
    </div>

    <% end %>

</div>