config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get "/menu", to: "items#index"
  resources :items, only: [:show, :index]

  resources :categories do
    resources :items, only: [:show, :index]
  end

  get "/cart", to: "cart#index"
  post "/cart", to: "cart#create"
  delete "/cart", to: "cart#delete"
  put "/cart", to: "cart#update"

  resources :orders, only: [:create, :index, :show, :update]

  get "/login", to: "sessions#new", :as => "login"
  post "/login", to: "sessions#create"
  get "/logout", to: 'sessions#destroy'
  delete "/logout", to: 'sessions#destroy'

  resources :users, only: [:show]

  namespace 'admin' do
    get '/', to: 'dashboard#index', as: '/'
    resources :items
    resources :categories
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, :description, presence: true
  has_many :items_categories
  has_many :items, :through => :items_categories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @categories = Category.all
    end
  end

  def edit
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      render :edit
    end
  end

  def new
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @category = Category.new
    end
  end

  def create
    if current_user.nil? || current_user.user?
      redirect_to root_path, alert: "Sensei says: 'Not quite yet young grasshopper'"
    else
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path
      else
        render :new
      end
    end
  end

  private

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @category = Category.all
  end


  def show
    @category = Category.find(params[:id])
  end

end

app/views/admin/categories/_form.html.erb
<%= form_for @category, url: {action: "create", controller: "admin/categories"} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>

<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit your category!</h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<li> <%= link_to 'Add New Category', new_admin_category_path %> </li>

<% @categories.each do |category| %>
  <div id="category_title"><%= category.title %></div>
  <div id="description"><%= category.description %></div>
  <div id="category_edit"> <td><%= link_to "Edit category", edit_admin_category_path(category) %></td>
<% end %>

app/views/admin/categories/new.html.erb
<h1>Create a new category!</h1>

<%= render 'form' %>