config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get "/menu", to: "items#index"
  resources :items, only: [:show, :index]

  resources :categories do
    resources :items, only: [:show, :index]
  end

  get "/cart", to: "cart#index"
  post "/cart", to: "cart#create"
  delete "/cart", to: "cart#delete"
  put "/cart", to: "cart#update"

  resources :orders, only: [:create, :index, :show, :update]

  get "/login", to: "sessions#new", :as => "login"
  post "/login", to: "sessions#create"
  get "/logout", to: 'sessions#destroy'
  delete "/logout", to: 'sessions#destroy'

  resources :users, only: [:show]

  namespace 'admin' do
    get '/', to: 'dashboard#index', as: '/'
    resources :items
    resources :categories
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ルビー食品</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <style>

    body {
        background-color: black;
        color: white;
        width: 95%;
        margin: 0 auto;

    }


    .button_to {color: black;}

    input {color: black;}

    </style>

  </head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href='/'>
        <%if !current_user.nil? %>
          <%if current_user.display_name %>
            Welcome <%= current_user.display_name%>
          <% else %>
            Welcome <%= current_user.full_name %>
          <% end %>
        <% else %>
        Welcome to Rubī shokuhin: ルビー食品
      <% end %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/menu">Menu<span class="sr-only"></span></a></li>
        <li><a href="/cart">View Cart</a></li>
        <li><a href="/orders">View Past Orders</a></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Food Categories<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <div class="container">
              <div id="categories_sidebar">
                <% Category.all.each do |category| %>
                  <li> <%= link_to category.title, category_path(category) %> </li>
                <% end %>
              </div>
            </div>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "Your Profile", user_path(:profile)%></li>
              <li><%= link_to "Logout", logout_path %></li>
              <% else %>
              <li><%= link_to "User Login", login_path %></li>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class='flash' role="alert">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
</div>

<%= yield %>

</body>

</html>